services:
  go2rtc:
    image: alexxit/go2rtc@sha256:f394f6329f5389a4c9a7fc54b09fdec9621bbb78bf7a672b973440bbdfb02241
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
      - LOCAL_IP=${LOCAL_IP}
    ports:
      - "1984:1984"
      - "443:443"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    volumes:
      - ./go2rtc:/config
      - ./certs:/certs:ro
